#! /bin/sh

# Autostarts
sxhkd &
dunst &
picom &
/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 &

polybar -c ~/.config/polybar/config.bspwm fullbar &

xrandr --output LVDS-0 --brightness .6

~/Github/i3-battery-popup/i3-battery-popup -m "Low battery" -s ~/Github/i3-battery-popup/i3-battery-popup.wav -n -i ~/.local/share/icons/Newaita-dark/status/48/battery-low.svg &

udiskie &

~/.config/bspwm/xinput.sh
xsetroot -cursor_name left_ptr &

# Wallpaper
feh --bg-fill /home/devops/Pictures/dracula-purplish.png 
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          6
bspc config split_ratio          0.52
bspc config gapless_monocle      false


bspc config focus_follows_pointer false
bspc config auto_alternate true
bspc config auto_cancel true

# Material Colors
#bspc config normal_border_color "#313131"
#bspc config active_border_color "#82aaff"
#bspc config focused_border_color "#82aaff"
#bspc config presel_border_color "#ffcb6b"
#bspc config urgent_border_color "#f07178"
#bspc config focused_locked_border_color "#ffcb6b"

bspc config normal_border_color "#44475a"
bspc config focused_border_color "#bd93f9"
bspc config active_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config normal_frame_opacity 0.0


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Zathura state=tiled
bspc rule -a java-lang-Thread state=floating
bspc rule -a Welcome to Android Studio state=floating
bspc rule -a soffice.bin state=floating
bspc rule -a mpv state=pseudo_tiled

